use science_hub;
db.dropDatabase();

db.articles.insertMany([
    
    {
        title: "Lets learn about Metamorphosis",
        body: "Metamorphosis is a drastic change in an animal's appearance as it grows up. All animals change somewhat as they get older. In some species — such as humans, dogs or cats - young animals look like mini versions of their parents. Animals that go through metamorphosis experience much bigger changes. They might lose tails or grow legs or wings.This process is especially common in insects. Perhaps the most famous example is a butterfly. When a butterfly egg hatches, a caterpillar emerges. That caterpillar later becomes enclosed in a chrysalis. There, it grows wings and other adult body parts, emerging as a butterfly. This total overhaul of the insect’s body is known as “complete metamorphosis.” Other insects go through “incomplete metamorphosis.” That process involves changes that are less radical. Crickets, for instance, are born without wings. But for the most part, young crickets look mostly like small versions of adult crickets. Many amphibians go through metamorphosis, too. Frogs hatch as tadpoles.Those little swimmers later lose their tails and grow legs to hop around on land.Their gills also disappear and their lungs take over for breathing.Metamorphosis is also seen in sea dwellers such as sea stars, crabs and clams."
     
    },

    {
        title: "What is the biggest animal in the world?",
        body: "It is worth noting that the largest living animals in the world today aren't land animals, because on land they must struggle against the forces of gravity to survive, effectively limiting their size. The creatures of the oceans can grow much larger, because the buoyancy of the water offers relief from gravity’s effects, allowing them the freedom to grow to gigantic proportions. The largest animal ever lives in the sea. The biggest animal in the world is the adult blue whale. These animals are bigger than any dinosaur that ever lived, and they are far bigger than the largest living land animal on the planet today. Blue whales can grow up to 105 feet long (32 m). That’s more than twice as long as a semi-trailer rolling along the highway. An adult blue whale weighs as much as 15 school buses."
    },

    {
        title: "Lets Learn about Bones!",
        body: "Your legs are attached to a circular group of bones called your pelvis. The pelvis is a bowl-shaped structure that supports the spine. It is made up of the two large hip bones in front, and behind are the sacrum and the coccyx. The pelvis acts as a tough ring of protection around parts of the digestive system, parts of the urinary system, and parts of the reproductive system.Your leg bones are very large and strong to help support the weight of your body. The bone that goes from your pelvis to your knee is called the femur (say: FEE-mur), and it's the longest bone in your body. At the knee, there's a triangular-shaped bone called the patella (say: puh-TEL-luh), or kneecap, that protects the knee joint. Below the knee are two other leg bones: the tibia (say: TIH-bee-uh) and the fibula (say: FIH-byuh-luh). Just like the three bones in the arm, the three bones in the leg are wider at the ends than in the middle to give them strength. "
    
    },

    {
        title: "Periodic table",
        body: "The Periodic Table is a way of listing the elements. Elements are listed in the table by the structure of their atoms. This includes how many protons they have as well as how many electrons they have in their outer shell. From left to right and top to bottom, the elements are listed in the order of their atomic number, which is the number of protons in each atom.It is called 'periodic' because elements are lined up in cycles or periods. From left to right elements are lined up in rows based on their atomic number (the number of protons in their nucleus). Some columns are skipped in order for elements with the same number of valence electrons to line up on the same columns. When they are lined up this way, elements in the columns have similar properties.Each horizontal row in the table is a period. There are seven (or eight) total periods. The first one is short and only has two elements, hydrogen and helium. The sixth period has 32 elements. In each period the left most element has 1 electron in its outer shell and the right most element has a full shell.Each element has its own name and abbreviation in the periodic table. Some of the abbreviations are easy to remember, like H for hydrogen. Some are a bit harder like Fe for iron or Au for gold. For gold the 'Au' comes from the Latin word for gold 'aurum'. Elements found on Earth and Mars are exactly the same.Hydrogen is the most common element found in the universe. It is also the lightest element.Isotopes are atoms of the same element, with different numbers of neutrons.In ancient times the elements referred to fire, earth, water, and air.Helium is the second most common element in the universe, but is very rare on the Earth.The elements that are generally considered metalloids include boron, silicon, germanium, arsenic, antimony, and tellurium. Other elements such as selenium and polonium are sometimes included as well."
    
    },
    
    {
        title: "Why are mitochondria called the powerhouse of cells?",
        body: "Mitochondria are referred to as the powerhouse of the cell or energy factories because they help in extracting energy from food via cellular respiration. The energy is released in the form of adenosine triphosphate (ATP). It is also called the energy currency of the cell. Powerhouse function: During digestion, food breaks down and products from digestion of food find their way into the cell then a series of chemical reactions occur in the cytoplasm. This permits some of the energy locked up in these products to be released and incorporated into the universal energy supplier in cells called ATP. From this process, remaining molecular fragments then enter the mitochondria and there they are finally converted into carbon dioxide and water. In these fragments, the energy locked up is incorporated into more ATP. The ATP produced can be used by the cell to supply energy required to function."
    
    },
    
    {
        title: "What lies at the Centre of a galaxy?",
        body: "The Galactic Center is the rotational center, the barycenter, of the Milky Way galaxy. Its central massive object is a supermassive black hole of about 4 million solar masses, which is called Sagittarius A*, a compact radio source which is almost exactly at the galactic rotational center. The Galactic Center is approximately 8 kiloparsecs (26,000 ly) away from Earth in the direction of the constellations Sagittarius, Ophiuchus, and Scorpius, where the Milky Way appears brightest, visually close to the Butterfly Cluster (M6) or the star Shaula, south to the Pipe Nebula. There are around 10 million stars within one parsec of the Galactic Center, dominated by red giants, with a significant population of massive supergiants and Wolf–Rayet stars from star formation in the region around 1 million years ago. The core stars are a small part within the much wider galactic bulge."
    },
    
    {
        title: "Who really discovered the law of gravity?",
        body: "Everyone knows that Isaac Newton came up with the law of gravity after seeing an apple fall from a tree in his mother’s garden. Newton himself told the story to several contemporaries, who recorded it for posterity. Ever since, Newton has been credited with discovering the law, describing how “All celestial bodies whatsoever have an attraction or gravitating power towards their own centres”. But these words are not Newton’s. They were penned by his scientific rival Robert Hooke in 1670, decades before Newton started telling people the apple story. This has led some historians to suspect Newton deliberately made up the story of the apple to back his claim to priority. While Hooke is best known today for a dull law about springs, he was one of the most brilliant scientists of his time, and made a host of discoveries. He even showed Newton to be wrong on an esoteric point concerning falling bodies. This did not go down well with the pathologically prickly Newton, who seems to have set about showing he had worked on gravity years before Hooke, leading to his claim about being inspired by the apple back in 1666. No one doubts that Newton made the biggest contribution to understanding gravity, but sadly for Hooke, Newton wanted to have the credit for everything."
    },

    {
        title: "What is a satellite?",
        body: "A satellite is an object in space that orbits or circles around a bigger object. There are two kinds of satellites: natural (such as the moon orbiting the Earth) or artificial (such as the International Space Station orbiting the Earth). There are dozens upon dozens of natural satellites in the solar system, with almost every planet having at least one moon. Saturn, for example, has at least 53 natural satellites, and between 2004 and 2017, it also had an artificial one — the Cassini spacecraft, which explored the ringed planet and its moons. Artificial satellites, however, did not become a reality until the mid-20th century. The first artificial satellite was Sputnik, a Russian beach-ball-size space probe that lifted off on Oct. 4, 1957. That act shocked much of the western world, as it was believed the Soviets did not have the capability to send satellites into space. Other countries began to send their own satellites into space as the benefits rippled through society. Weather satellites improved forecasts, even for remote areas. Land-watching satellites such as the Landsat series (on its ninth generation now) tracked changes in forests, water and other parts of Earth's surface over time. Telecommunications satellites made long-distance telephone calls and eventually, live television broadcasts from across the world became a normal part of life. Later generations helped with Internet connections. With the miniaturization of computers and other hardware, it's now possible to send up much smaller satellites that can do science, telecommunications or other functions in orbit. It's common now for companies and universities to create 'CubeSats', or cube-shaped satellites that frequently populate low-Earth orbit."
    },
    
    {
       title: "The miracle of a natural diamond – how diamonds are formed",
       body: "Natural diamonds can be formed in at least four completely different but equally exceptional ways, however just one of these formation processes accounts for nearly all of the diamonds we see today. Natural diamonds were born deep below the earth’s surface in environments of extreme pressure and temperature. At depths of over 120km, through intense heat of between 900°C and 1300°C, pressures of 45 kbar and above and over millions and often billions of years, this incredible miracle happens – carbon crystallises to form diamonds. In order to continue this extraordinary journey, the diamonds need to be released from the intense pressure and heat under which they are formed in order to embark upon their voyage to the earth’s surface.This happens when an event deep in the earth causes a part of the mantle to melt into magma which then erupts rapidly to the surface of the earth, transporting diamonds from great depths. As the magma cools, it hardens to form the rock called kimberlite, mainly in vertical structures known as kimberlite pipes. These are the most significant source of diamonds, accounting for nearly all natural diamonds. However, of the 15% of kimberlite pipes that have been discovered across the world that contain diamonds, only 1% are economically viable, highlighting how truly rare diamonds are."
    }
        
])